[package]
name = "rustcii"
version = "0.1.0"
authors = ["DrPandemic"]

[dependencies]
image = "*"
imageproc = "*"
rusttype = "*"
rayon = "*"
itertools = "0.8"
clap = {version = "2.32", features = ["yaml"]}

[profile.release]
debug = true