[package]
name = "rustcii"
version = "0.1.0"
authors = ["DrPandemic"]

[dependencies]
image = "*"
imageproc = "*"
rusttype = "*"
rayon = "*"
itertools = "0.8"
terminal_size = "*"

[profile.release]
debug = true